### model
model_name_or_path: /apdcephfs_gy2/share_303094202/ralphzhou/models/Qwen2.5-32B-Instruct
use_unsloth_gc: true
seed: 42
enable_liger_kernel: true
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_partial_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: gaia_train_scored_planner
#dataset_dir: ../data
template: qwen
cutoff_len: 33768
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /apdcephfs_gy2/share_303094202/ralphzhou/train_result/all_qwen2_32B_planner_scored
logging_steps: 1
save_steps: 20
plot_loss: true

### train
per_device_train_batch_size: 1 # this must be set to 1 for now!!!
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
full_determinism: true

report_to: wandb
run_name: qwen2_32B_planner_scored_1e-5

hub_strategy: every_save
push_to_hub: true
push_to_hub_organization: owl-agent
push_to_hub_model_id: all_qwen2_32B_planner_scored
